language: java

sudo: required
services:
  - docker

jobs:
  include:
    - stage: maven
      script:
        - mvn clean test package
    - stage: docker
      script:
        - mvn dockerfile:build
        - mvn dockerfile:tag@tag-version
    - stage: push
      # if: branch = master
      script:
        - docker images
        # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # - mvn dockerfile:push@push-version
        # - mvn dockerfile:push@push-latest
      
