version: '3.3'

services:
   app:
     image: jrmcdonald/padx-scraper:0.4.0
     restart: always
     ports:
      - 80:8080
     environment:
      - LOGGING_LEVEL_COM_JRMCDONALD=INFO
      - SPRING_PROFILES_ACTIVE=prod